### ISSUE TITLE
submitblock RPC rejections

### ISSUE THREAD

**Issue by oliverw** [digibyte/digibyte#115]
We are getting roughly 40% of our mined blocks rejected by the daemon (see log below) using 6.16.1 Beta compiled on Debian 9.3. I'm not sure if there's an issue with our pool software's handling of Digibyte's PoW/Pos hybrid nature: 

https://github.com/coinfoundry/miningcore/blob/master/src/MiningCore/Blockchain/Bitcoin/BitcoinJob.cs

> ThreadRPCServer method=submitblock
> InvalidChainFound: invalid block=1392a5e4216dafa52d7b  height=1950683  trust=1950684  date=03/13/18 17:00:43
> InvalidChainFound:  current best=6e5ad73c3d1d076a9054  height=1950682  trust=1950683  date=03/13/18 16:59:38
> ERROR: SetBestChain() : SetBestChainInner failed
> ERROR: AcceptBlock() : AddToBlockIndex failed
> ERROR: ProcessBlock() : AcceptBlock FAILED
>

**Comment by sam-semillia** [comment]
Hi,

how could you solve the problem?

Thanks, br

**Comment by sam-semillia** [comment]
Hi,

how could you solve the problem?

Thanks, br


> We are getting roughly 40% of our mined blocks rejected by the daemon (see log below) using 6.16.1 Beta compiled on Debian 9.3. I'm not sure if there's an issue with our pool software's handling of Digibyte's PoW/Pos hybrid nature:
> 
> https://github.com/coinfoundry/miningcore/blob/master/src/MiningCore/Blockchain/Bitcoin/BitcoinJob.cs
> 
> > ThreadRPCServer method=submitblock
> > InvalidChainFound: invalid block=1392a5e4216dafa52d7b  height=1950683  trust=1950684  date=03/13/18 17:00:43
> > InvalidChainFound:  current best=6e5ad73c3d1d076a9054  height=1950682  trust=1950683  date=03/13/18 16:59:38
> > ERROR: SetBestChain() : SetBestChainInner failed
> > ERROR: AcceptBlock() : AddToBlockIndex failed
> > ERROR: ProcessBlock() : AcceptBlock FAILED

**Comment by ChillingSilence** [comment]
You need to be running 6.16.5.1, as 6.16.1 is before the Bitcoin inflation bug.

**Comment by sam-semillia** [comment]
Hi,

I'm running on that version, but it seems as I'm currently facing a different problem. I only receive as a response the term "invalid" for block 7767655. Do you have any ideas? Debug log is attached.

Thanks, br

2018-12-01T20:13:44Z UpdateTip: new best=dc4fb46f5a65906b328206aaab8bb3212126282592af8ac08c5b74fa2d47a481 height=7767654 version=0x20000602 algo=3 (skein) log2_work=80.510776 tx=17447088 date='2018-12-01T20:13:29Z' progress=1.000000 cache=0.2MiB(1207txo)
2018-12-01T20:13:45Z block height for reward is 7767655
2018-12-01T20:13:45Z CreateNewBlock(): block weight: 812 txs: 0 fees: 0 sigops 400
2018-12-01T20:13:45Z block height for reward is 7767655
2018-12-01T20:14:03Z ERROR: ProcessNewBlock: AcceptBlock FAILED (high-hash, proof of work failed (code 16))
2018-12-01T20:14:05Z ERROR: ProcessNewBlock: AcceptBlock FAILED (high-hash, proof of work failed (code 16))
2018-12-01T20:14:14Z ERROR: ProcessNewBlock: AcceptBlock FAILED (high-hash, proof of work failed (code 16))
2018-12-01T20:14:16Z block height for reward is 7767655
2018-12-01T20:14:16Z CreateNewBlock(): block weight: 3792 txs: 2 fees: 76622 sigops 416
2018-12-01T20:14:16Z block height for reward is 7767655
2018-12-01T20:14:20Z block height for reward is 7767655
2018-12-01T20:14:20Z UpdateTip: new best=126ac31332976dbc47f46358c2e804d94741e4de0f6752c3c317e7fe4334276f height=7767655 version=0x20000402 algo=2 (groestl) log2_work=80.510777 tx=17447089 date='2018-12-01T20:14:08Z' progress=1.000000 cache=0.2MiB(1212txo)
2018-12-01T20:14:21Z block height for reward is 7767656

**Comment by cornac** [comment]
Show your digibyte.conf

**Comment by sam-semillia** [comment]
#
# JSON-RPC options (for controlling a running DigiByte/digibyted process)
#

# server=1 tells DigiByte-Qt and digibyted to accept JSON-RPC commands
server=1

# Bind to given address to listen for JSON-RPC connections. Use [host]:port notation for IPv6.
# This option can be specified multiple times (default: bind to all interfaces)
#rpcbind=<addr>

# If no rpcpassword is set, rpc cookie auth is sought. The default `-rpccookiefile` name
# is .cookie and found in the `-datadir` being used for digibyted. This option is typically used
# when the server and client are run as the same user.
#
# If not, you must set rpcuser and rpcpassword to secure the JSON-RPC api. The first
# method(DEPRECATED) is to set this pair for the server and client:
rpcuser=user
rpcpassword=pass
#
# The second method `rpcauth` can be added to server startup argument. It is set at initialization time
# using the output from the script in share/rpcauth/rpcauth.py after providing a username:
#
# ./share/rpcauth/rpcauth.py alice
# String to be appended to digibyte.conf:
# rpcauth=alice:f7efda5c189b999524f151318c0c86$d5b51b3beffbc02b724e5d095828e0bc8b2456e9ac8757ae3211a5d9b16a22ae
# Your password:
# DONT_USE_THIS_YOU_WILL_GET_ROBBED_8ak1gI25KFTvjovL3gAM967mies3E=
#
# On client-side, you add the normal user/password pair to send commands:
#rpcuser=alice
#rpcpassword=DONT_USE_THIS_YOU_WILL_GET_ROBBED_8ak1gI25KFTvjovL3gAM967mies3E=
#
# You can even add multiple entries of these to the server conf file, and client can use any of them:
# rpcauth=bob:b2dd077cb54591a2f3139e69a897ac$4e71f08d48b4347cf8eff3815c0e25ae2e9a4340474079f55705f40574f4ec99

# How many seconds digibyte will wait for a complete RPC HTTP request.
# after the HTTP connection is established. 
#rpcclienttimeout=30

# By default, only RPC connections from localhost are allowed.
# Specify as many rpcallowip= settings as you like to allow connections from other hosts,
# either as a single IPv4/IPv6 or with a subnet specification.

# NOTE: opening up the RPC port to hosts outside your local trusted network is NOT RECOMMENDED,
# because the rpcpassword is transmitted over the network unencrypted.

# server=1 tells DigiByte-Qt to accept JSON-RPC commands.
# it is also read by digibyted to determine if RPC should be enabled 
#rpcallowip=10.1.1.34/255.255.255.0
#rpcallowip=1.2.3.4/24
#rpcallowip=2001:db8:85a3:0:0:8a2e:370:7334/96

# Listen for RPC connections on this TCP port:
rpcport=8332

# You can use DigiByte or digibyted to send commands to DigiByte/digibyted
# running on another host using this option:
#rpcconnect=127.0.0.1

**Comment by sam-semillia** [comment]
`#
# JSON-RPC options (for controlling a running DigiByte/digibyted process)
#

# server=1 tells DigiByte-Qt and digibyted to accept JSON-RPC commands
server=1

# Bind to given address to listen for JSON-RPC connections. Use [host]:port notation for IPv6.
# This option can be specified multiple times (default: bind to all interfaces)
#rpcbind=<addr>

# If no rpcpassword is set, rpc cookie auth is sought. The default `-rpccookiefile` name
# is .cookie and found in the `-datadir` being used for digibyted. This option is typically used
# when the server and client are run as the same user.
#
# If not, you must set rpcuser and rpcpassword to secure the JSON-RPC api. The first
# method(DEPRECATED) is to set this pair for the server and client:
rpcuser=user
rpcpassword=pass
#
# The second method `rpcauth` can be added to server startup argument. It is set at initialization time
# using the output from the script in share/rpcauth/rpcauth.py after providing a username:
#
# ./share/rpcauth/rpcauth.py alice
# String to be appended to digibyte.conf:
# rpcauth=alice:f7efda5c189b999524f151318c0c86$d5b51b3beffbc02b724e5d095828e0bc8b2456e9ac8757ae3211a5d9b16a22ae
# Your password:
# DONT_USE_THIS_YOU_WILL_GET_ROBBED_8ak1gI25KFTvjovL3gAM967mies3E=
#
# On client-side, you add the normal user/password pair to send commands:
#rpcuser=alice
#rpcpassword=DONT_USE_THIS_YOU_WILL_GET_ROBBED_8ak1gI25KFTvjovL3gAM967mies3E=
#
# You can even add multiple entries of these to the server conf file, and client can use any of them:
# rpcauth=bob:b2dd077cb54591a2f3139e69a897ac$4e71f08d48b4347cf8eff3815c0e25ae2e9a4340474079f55705f40574f4ec99

# How many seconds digibyte will wait for a complete RPC HTTP request.
# after the HTTP connection is established. 
#rpcclienttimeout=30

# By default, only RPC connections from localhost are allowed.
# Specify as many rpcallowip= settings as you like to allow connections from other hosts,
# either as a single IPv4/IPv6 or with a subnet specification.

# NOTE: opening up the RPC port to hosts outside your local trusted network is NOT RECOMMENDED,
# because the rpcpassword is transmitted over the network unencrypted.

# server=1 tells DigiByte-Qt to accept JSON-RPC commands.
# it is also read by digibyted to determine if RPC should be enabled 
#rpcallowip=10.1.1.34/255.255.255.0
#rpcallowip=1.2.3.4/24
#rpcallowip=2001:db8:85a3:0:0:8a2e:370:7334/96

# Listen for RPC connections on this TCP port:
rpcport=8332

# You can use DigiByte or digibyted to send commands to DigiByte/digibyted
# running on another host using this option:
#rpcconnect=127.0.0.1`

**Comment by sam-semillia** [comment]
Copy paste didn't quite work :D

https://pastebin.com/hG0kTG9K

**Comment by cornac** [comment]
You need to add algo property
Like this “algo=sha256d”

**Comment by sam-semillia** [comment]
does that mean, that i can't mine sha and scrypt with the same wallet?

**Comment by cornac** [comment]
Yes. One algo = one instance.

**Comment by sam-semillia** [comment]
ahhh, ok, thanks! can i install 2 instances on the same machine somehow?

**Comment by cornac** [comment]
Copy your .digibate dir, in conf change ports for rpc and p2p and delete or rename  wallet.dat to create new wallet.    use  parameter -datadir=new_digibyte_path when start second  digibyted instance. 
It works fine on my pool https://dgb-mining.club

**Comment by cornac** [comment]
And don’t forget make port forwarding on network hardware

**Comment by sam-semillia** [comment]
thanks so much, you helped me a lot!!

**Comment by seperatis** [comment]
> Yes. One algo = one instance.

This is no longer true. You can now run a pool with all DGB algo's at once with ONE single instance of Digibyte daemon. You simply need to get gbtArgs in your coin.json file.

Quoting from @oliverw below:

> CF is running digibyted without any config file whatsoever. All pools point to the same digibyted instance (same port, same password, same user etc). The pools only have different values for gbtArgs in their configuration in Miningcore's config.json.

`"gbtArgs": [{"rules": [ "segwit" ]}, "sha256d"], "gbtArgs": [{"rules": [ "segwit" ]}, "scrypt"],`

etc.

**Comment by ChillingSilence** [comment]
> > Yes. One algo = one instance.
> 
> This is no longer true. You can now run a pool with all DGB algo's at once with ONE single instance of Digibyte daemon. You simply need to get gbtArgs in your coin.json file.

Correct, this changed in 6.17.2:
https://github.com/digibyte/digibyte/releases/tag/v6.17.2

Further confirmation:
https://medium.com/@josiah_digibyte/heres-digibyte-core-6-17-2-f77faa2b70ee

Please note that development has moved from digibyte/digibyte to digibyte-core/digibyte , thanks :)
