### ISSUE TITLE
qmake error

### ISSUE THREAD

**Issue by mapleshadow** [digibyte/digibyte#3]
Project MESSAGE: Building with QRCode support
Project MESSAGE: Building without UPNP support
Project MESSAGE: Building with QRCode support
Project MESSAGE: Building with UPNP support
Removed plural forms as the target language has less forms.
If this sounds wrong, possibly the target language is not set or recognized.
WARNING: TARGET is empty

WHY????

**Comment by ghost** [comment]
If you're using QT5 you should try using QT4 instead.
The error you're getting about the Target being empty is common with QT5, as they changed the default settings. You could change "target = " to "target = digibyte-qt" in the digibyte-qt.pro file, which would allow you to actually try to build the project, but (If you're indeed using QT5) it will fail later due to the use of functions that were deprecated in QT5.
If that is not the case, just ignore my rambling. ;-)

**Comment by digibyte** [comment]
Did you use the "Make" command after running "qmake "USE_UPNP=-" digibyte-qt.pro" ?

Or on Windows it is "make -f Makefile.Release"

We get this message every time we compile.

**Comment by mapleshadow** [comment]
qmake-qt4 is ok~~~
