### ISSUE TITLE
RPC Solomining should be reintroduced

### ISSUE THREAD

**Issue by bathrobehero** [digibyte/digibyte#80]
Solomining doesn't work anymore which is a problem. ("JSON-RPC call failed: Method not found")

It was removed from Bitcoin-qt because not many people solomines it anymore but for Digibyte it should be reintroduced to combat centralization and pools being too powerful. Given there are multiple algorithms in Digibyte it's arguably easy to solomine blocks with a few GPU rigs. And there's no benefit to removing solomining.

Without solomining the network is also smaller because it becomes pointless for miners to run the wallet 0-24h.

So please, reintroduce RPC mining.

**Comment by SCP-168** [comment]
!

**Comment by win98boy** [comment]
The same problem!
("JSON-RPC call failed: Method not found")
("JSON-RPC call failed: Method not found")
("JSON-RPC call failed: Method not found")

**Comment by win98boy** [comment]
i have about 100G to solo it,but it's not work, too.
i want soloing..........ing.......
please, help me!

**Comment by digibyte** [comment]
It is still possible to solo mine with getblocktemplate. This is what we used during testing for the most recent updates.  We solo mined on all 5 algos with GPU and CPU for testing. Please reference this: https://en.bitcoin.it/wiki/Getblocktemplate

"Due to scalability problems, JSON-RPC stack has not been able to keep up with the hash rates needed for solo mining today."

Depending on which hardware you are mining on some software does not getblocktemplate ASIC solo mining (BFG). While other GPU miners you may need to set a flag to keep the miner from trying getblock by default. There are several variations of mining software out there now with different parameters.

**Comment by imrecsoka** [comment]
I have the older version wallet , if anybody wants it, please e-mail me.
Thanks
icsoka21   @   hotmail  dot com   and dont spam me please

**Comment by bathrobehero** [comment]
"Due to scalability problems, JSON-RPC stack has not been able to keep up with the hash rates needed for solo mining today."

It works perfectly with dozens of algos with plenty of coins for years. It works perfectly with the older wallet as well and always has been.

GBT is annoying and not supported in nvidia's ccminers, only in one that is slow. And even that is sketchy with GBT.

**Comment by ChillingSilence** [comment]
There is no plan to reintroduce legacy mining methods at this time. Ccminer and others should be updated to support current mining methods, or for any user "solo" user who has enough rigs / ASICs to mine and solo-find blocks, should investigate running their own "pool" software for best performance / redundancy.
